name: Deploy

on:
  push:
    branches:
      - main

jobs:

  deploy:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout

        uses: actions/checkout@v2

      - name: Deployment

        uses: appleboy/ssh-action@main

        with:

          host: ${{ secrets.SSH_HOST }}

          key: ${{ secrets.KEY }}

          username: samolet500

          script: |

            cd /home/s/samolet500/maxmotus/public_html

            git checkout -f 

            git pull
